// /lib/proveedores/mocks.ts
import { Supplier } from "./types";

export const suppliersMock: Supplier[] = [
  {
    id: 1,
    codigo: "PROV001",
    tipo: "empresa",
    razonSocial: "Distribuidora San Martín S.A.",
    nombreCompleto: "Carlos Rodriguez",
    nombreFantasia: "Distribuidora San Martín",
    categoriaFiscal: "Responsable Inscripto",
    cuitCuil: "30-12345678-9",
    pais: "Argentina",
    codigoPostal: "1000",
    provincia: "Buenos Aires",
    localidad: "Capital Federal",
    zona: "Centro",
    barrio: "Microcentro",
    telefono: "+54 11 4567 8901",
    email: "contacto@distribuidorasanmartin.com",
    paginaWeb: "https://www.distribuidorasanmartin.com",
    estado: "Activo",
    fechaRegistro: "2024-01-15",
  },
  {
    id: 2,
    codigo: "PROV002",
    tipo: "persona",
    nombreCompleto: "María Elena Fernández",
    nombreFantasia: "Ferretería El Martillo",
    genero: "Femenino",
    categoriaFiscal: "Monotributista",
    cuitCuil: "27-23456789-3",
    pais: "Argentina",
    codigoPostal: "1425",
    provincia: "Buenos Aires",
    localidad: "Capital Federal",
    zona: "Norte",
    barrio: "Belgrano",
    telefono: "+54 11 4789 0123",
    email: "maria@elmartillo.com",
    paginaWeb: "",
    estado: "Activo",
    fechaRegistro: "2024-01-10",
  },
  {
    id: 3,
    codigo: "PROV003",
    tipo: "empresa",
    razonSocial: "Tecnología Avanzada S.R.L.",
    nombreCompleto: "Roberto Silva",
    nombreFantasia: "TechAdvanced",
    categoriaFiscal: "Responsable Inscripto",
    cuitCuil: "30-34567890-1",
    pais: "Argentina",
    codigoPostal: "1640",
    provincia: "Buenos Aires",
    localidad: "Martínez",
    zona: "Norte",
    barrio: "Centro",
    telefono: "+54 11 4890 1234",
    email: "info@techadvanced.com.ar",
    paginaWeb: "https://www.techadvanced.com.ar",
    estado: "Activo",
    fechaRegistro: "2024-01-08",
  },
  {
    id: 4,
    codigo: "PROV004",
    tipo: "empresa",
    razonSocial: "Alimentos del Sur S.A.",
    nombreCompleto: "Ana Gutierrez",
    nombreFantasia: "AlimSur",
    categoriaFiscal: "Responsable Inscripto",
    cuitCuil: "30-45678901-2",
    pais: "Argentina",
    codigoPostal: "2000",
    provincia: "Santa Fe",
    localidad: "Rosario",
    zona: "Centro",
    barrio: "Centro",
    telefono: "+54 341 456 7890",
    email: "ventas@alimsur.com",
    paginaWeb: "https://www.alimsur.com",
    estado: "Activo",
    fechaRegistro: "2024-01-05",
  },
  {
    id: 5,
    codigo: "PROV005",
    tipo: "persona",
    nombreCompleto: "Juan Carlos Pérez",
    nombreFantasia: "Librería Pérez",
    genero: "Masculino",
    categoriaFiscal: "Monotributista",
    cuitCuil: "20-56789012-4",
    pais: "Argentina",
    codigoPostal: "5000",
    provincia: "Córdoba",
    localidad: "Córdoba",
    zona: "Centro",
    barrio: "Nueva Córdoba",
    telefono: "+54 351 567 8901",
    email: "juan@libreriaperez.com",
    paginaWeb: "",
    estado: "Activo",
    fechaRegistro: "2024-01-03",
  },
  {
    id: 6,
    codigo: "PROV006",
    tipo: "empresa",
    razonSocial: "Construcciones del Norte S.A.",
    nombreCompleto: "Diego Morales",
    nombreFantasia: "ConNorte",
    categoriaFiscal: "Responsable Inscripto",
    cuitCuil: "30-67890123-5",
    pais: "Argentina",
    codigoPostal: "4000",
    provincia: "Tucumán",
    localidad: "San Miguel de Tucumán",
    zona: "Centro",
    barrio: "Centro",
    telefono: "+54 381 678 9012",
    email: "info@connorte.com.ar",
    paginaWeb: "https://www.connorte.com.ar",
    estado: "Activo",
    fechaRegistro: "2024-01-01",
  },
  {
    id: 7,
    codigo: "PROV007",
    tipo: "empresa",
    razonSocial: "Textiles Modernos S.R.L.",
    nombreCompleto: "Laura Vega",
    nombreFantasia: "TexMod",
    categoriaFiscal: "Responsable Inscripto",
    cuitCuil: "30-78901234-6",
    pais: "Argentina",
    codigoPostal: "3000",
    provincia: "Santa Fe",
    localidad: "Santa Fe",
    zona: "Este",
    barrio: "Candioti",
    telefono: "+54 342 789 0123",
    email: "contacto@texmod.com",
    paginaWeb: "https://www.texmod.com",
    estado: "Activo",
    fechaRegistro: "2023-12-28",
  },
  {
    id: 8,
    codigo: "PROV008",
    tipo: "persona",
    nombreCompleto: "Patricia Ruiz",
    nombreFantasia: "Farmacia Central",
    genero: "Femenino",
    categoriaFiscal: "Monotributista",
    cuitCuil: "27-89012345-7",
    pais: "Argentina",
    codigoPostal: "1900",
    provincia: "Buenos Aires",
    localidad: "La Plata",
    zona: "Centro",
    barrio: "Centro",
    telefono: "+54 221 890 1234",
    email: "patricia@farmaciacentral.com",
    paginaWeb: "",
    estado: "Inactivo",
    fechaRegistro: "2023-12-25",
  },
];
